---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycontainer
spec:
  selector:
    matchLabels:
      app: container
  replicas: 1
  template:
    metadata:
      labels:
        app: container
    spec:
      containers:
        - name: main
          image: busybox
          command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']

